import { ManufacturerId } from "./manufacturer";
import { OperatorId } from "./operator";
import { CreationType } from "./creation_type";
import { Usage } from "./creation_usage";
import { Status } from "./status";

import { TYPE_MAP, USAGE_MAP, TypeMapLetters, UsageMapLetters } from "../utility/code_mapping";


export type CreationCode = `${TypeMapLetters}${UsageMapLetters}${string}`;
export type CreationId = number;


export class CreationLite {
    id: CreationId;
    code: CreationCode;
    name: string;
    type: CreationType;
    usage: Usage;
    last_update: Date;
    status: Status;

    constructor(
        id: CreationId,
        code: CreationCode | null,
        name: string,
        type: CreationType,
        usage: Usage,
        last_update: Date,
        status: Status
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.usage = usage;
        this.last_update = last_update;
        this.status = status;

        if (code === null) {
            this.code = this.generateCode();
        } else {
            this.code = code;
        }
    }

    /**
     * Generates a creation code based on the type and usage of the creation. The code is generated by concatenating the type letter, usage letter, and the date undert the format YYMMDDHHMM The type and usage letters are determined by the TYPE_MAP and USAGE_MAP respectively.
    * @returns The generated creation code.
     * @throws Error if the type or usage of the creation is unknown.
     */
    public generateCode(): CreationCode {
        const typeLetter = TYPE_MAP[this.type];
        const usageLetter = USAGE_MAP[this.usage];

        const now = new Date();
        const year = now.getFullYear() % 100; // Get last two digits of the year
        const month = now.getMonth() + 1; // Months are zero-based, so add 1
        const day = now.getDate();
        const hours = now.getHours();
        const minutes = now.getMinutes();

        // Format the date and time as YYMMDDHHMM
        const formattedDate = `${year.toString().padStart(2, '0')}${month.toString().padStart(2, '0')}${day.toString().padStart(2, '0')}${hours.toString().padStart(2, '0')}${minutes.toString().padStart(2, '0')}`;

        
        if (!typeLetter || !usageLetter) {
            throw new Error("Cannot generate code for unknown type or usage.");
        }

        return `${typeLetter}${usageLetter}${formattedDate}` as CreationCode;      
    }
}

export class Creation extends CreationLite {
    description: string;
    workshop_link: string;
    manufacturer: ManufacturerId | null;
    operator: OperatorId | null;
    creation_date: Date;

    constructor(
        id: CreationId,
        code: CreationCode,
        name: string,
        description: string,
        workshop_link: string,
        manufacturer: ManufacturerId | null,
        operator: OperatorId | null,
        type: CreationType,
        usage: Usage,
        creation_date: Date,
        status: Status,
        last_update: Date,
    ) {
        super(id, code, name, type, usage, last_update, status);
        this.description = description;
        this.workshop_link = workshop_link;
        this.manufacturer = manufacturer;
        this.operator = operator;
        this.creation_date = creation_date;
    }
}
