
export enum Usage {
    UNKNOWN,
    SEARCH_AND_RESCUE,
    FIRE_FIGHTING,
    TRANSPORT,
    COMBAT,
    RESEARCH,
    EXPLORATION,
    RECREATIONAL,
    SURVEILLANCE,
    COMMUNICATIONS,
    CONSTRUCTION,
    MINING,
    AGRICULTURE,
    FISHING,
    TOURISM,
}